spring:
  application:
    name: @artifactId@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    # 连接池配置
    initial-size: 5
    min-idle: 10
    max-active: 80
    # 连接等待超时时间
    max-wait: 60000

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
      # 关闭超时时间
      shutdown-timeout: 600000


#mybatis
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.blog.core.**.dao

pagehelper:
  helperDialect:
  reasonable: false
  supportMethodsArguments: true
  params: count = countSql

# elasticsearch配置
#  data:
#    elasticsearch:
#      cluster-name: free-elasticsearch
#      cluster-nodes: 127.0.0.1:9200
