server:
  port: 8681
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  freemarker:
    check-template-location: false

#日志
logging:
  level:
    com.blog.core: DEBUG
    org.springframework.security: DEBUG
    com.blog.core.**.dao: DEBUG

blog:
  version: 1.0
  showsql: true

#开启日志记录
isOpenManageAopLog : true
